export type SenseOrgan = {
  id: string;
  name: string;
  tagline: string;
  description: string;
  color: string;
  icon: string;
  sections: {
    overview: string;
    anatomy: string[];
    functions: string[];
    diseases: { name: string; description: string }[];
    symptoms: string[];
    causes: string[];
    diagnosis: string[];
    tests: string[];
    treatment: string[];
    prevention: string[];
    homeRemedies: string[];
    nutrition: string[];
    lifestyle: string[];
    exercises: string[];
    faqs: { q: string; a: string }[];
    myths: { myth: string; fact: string }[];
    research: { title: string; summary: string }[];
    relatedConditions: string[];
    emergencyCare: string[];
    whenToVisit: string[];
    trustedResources: { name: string; url: string }[];
    videos: { title: string; videoId: string }[];
  };
};

export const senseOrgans: SenseOrgan[] = [
  {
    id: 'eye',
    name: 'Eye',
    tagline: 'The window to your world',
    description:
      'The eye is a remarkable sensory organ that detects light and converts it into electro-chemical impulses in neurons, allowing us to perceive the visual world.',
    color: 'hsl(var(--sense-eye))',
    icon: 'Eye',
    sections: {
      overview:
        'The human eye is an intricate organ responsible for vision. It works like a camera, capturing light and converting it into signals the brain interprets as images. The eye can distinguish about 10 million colors and process information at remarkable speeds.',
      anatomy: [
        'Cornea — the clear front window that focuses light entering the eye',
        'Iris — the colored part that controls how much light enters',
        'Pupil — the black circle that adjusts to light levels',
        'Lens — focuses light onto the retina, changing shape to focus on near/far objects',
        'Retina — the light-sensitive layer at the back, containing photoreceptors',
        'Macula — central retina area for sharp, detailed central vision',
        'Optic nerve — transmits visual information to the brain',
        'Vitreous humor — the gel filling the eye, maintaining its shape',
      ],
      functions: [
        'Light detection and image formation through the cornea and lens',
        'Color perception via three types of cone cells (red, green, blue)',
        'Depth perception through binocular vision from both eyes',
        'Light adaptation through pupil dilation and constriction',
        'Motion detection and tracking of moving objects',
        'Focus adjustment for near and far objects (accommodation)',
      ],
      diseases: [
        { name: 'Myopia (Nearsightedness)', description: 'Distant objects appear blurry while close objects are clear. Caused by the eyeball being too long or the cornea too curved.' },
        { name: 'Hyperopia (Farsightedness)', description: 'Near objects are blurry. Caused by the eyeball being too short or the cornea too flat.' },
        { name: 'Astigmatism', description: 'Irregular cornea shape causes distorted or blurred vision at all distances.' },
        { name: 'Cataracts', description: 'Clouding of the lens leading to blurry vision, common with aging.' },
        { name: 'Glaucoma', description: 'Damage to the optic nerve from increased pressure inside the eye, can cause irreversible vision loss.' },
        { name: 'Macular Degeneration', description: 'Deterioration of the macula affecting central vision, common in older adults.' },
        { name: 'Conjunctivitis (Pink Eye)', description: 'Inflammation or infection of the conjunctiva, causing redness and irritation.' },
        { name: 'Dry Eye Syndrome', description: 'Insufficient tear production or poor tear quality causing discomfort and potential damage.' },
      ],
      symptoms: [
        'Blurred or double vision',
        'Difficulty seeing at night',
        'Eye pain or pressure',
        'Redness or irritation',
        'Excessive tearing or dryness',
        'Sensitivity to light',
        'Floaters or flashes of light',
        'Sudden vision loss',
      ],
      causes: [
        'Aging and natural deterioration',
        'Genetics and family history',
        'Prolonged screen time and digital eye strain',
        'UV exposure without protection',
        'Chronic conditions like diabetes and hypertension',
        'Poor nutrition lacking key vitamins',
        'Eye injuries and trauma',
        'Infections and allergies',
      ],
      diagnosis: [
        'Visual acuity test using Snellen chart',
        'Slit-lamp examination for detailed eye structure view',
        'Tonometry to measure intraocular pressure',
        'Ophthalmoscopy to examine the retina and optic nerve',
        'Color vision testing with Ishihara plates',
        'Peripheral vision (visual field) test',
      ],
      tests: [
        'Snellen Chart Test — measures visual sharpness',
        'Ishihara Color Test — detects color blindness',
        'Amsler Grid — screens for macular degeneration',
        'Intraocular Pressure Test — screens for glaucoma',
        'Retinal Photography — documents retina health',
        'Cover Test — checks eye alignment',
      ],
      treatment: [
        'Prescription glasses or contact lenses for refractive errors',
        'LASIK and other refractive surgeries',
        'Cataract surgery with artificial lens implant',
        'Medicated eye drops for glaucoma to reduce pressure',
        'Anti-VEGF injections for macular degeneration',
        'Antibiotic drops for bacterial infections',
        'Artificial tears for dry eye management',
      ],
      prevention: [
        'Wear UV-protective sunglasses outdoors',
        'Follow the 20-20-20 rule for screen use',
        'Eat a diet rich in vitamins A, C, E, and omega-3s',
        'Get regular eye exams every 1-2 years',
        'Avoid smoking, which increases cataract and macular degeneration risk',
        'Wear protective eyewear during sports and hazardous activities',
        'Maintain good blood sugar and blood pressure control',
      ],
      homeRemedies: [
        'Warm compress for dry eyes and styes',
        'Cold compress for eye puffiness and irritation',
        'Cucumber slices to soothe tired eyes',
        'Rose water drops for natural eye refreshment',
        'Adequate sleep to allow eye restoration',
        'Palming exercise to relax eye muscles',
      ],
      nutrition: [
        'Vitamin A (carrots, sweet potatoes, spinach) — essential for retina function',
        'Lutein & Zeaxanthin (kale, eggs, corn) — protect the macula',
        'Omega-3 fatty acids (salmon, walnuts, flaxseed) — reduce dry eye risk',
        'Vitamin C (citrus, bell peppers) — supports blood vessels in eyes',
        'Vitamin E (almonds, sunflower seeds) — protects eye cells from damage',
        'Zinc (pumpkin seeds, chickpeas) — helps vitamin A reach the retina',
      ],
      lifestyle: [
        'Take regular screen breaks using the 20-20-20 rule',
        'Ensure proper lighting when reading or working',
        'Maintain a healthy weight to reduce diabetes risk',
        'Stay hydrated to support tear production',
        'Practice eye yoga and focus-shifting exercises',
        'Get 7-8 hours of sleep for eye recovery',
      ],
      exercises: [
        'Palming: rub hands warm, cup over closed eyes for 30 seconds',
        'Figure-8: trace a large figure-8 with your eyes 10 times',
        'Near-far focus: switch focus between thumb and distant object',
        'Eye rolling: roll eyes clockwise and counterclockwise 10 times',
        'Blinking: blink rapidly 20 times to refresh tear film',
      ],
      faqs: [
        { q: 'How often should I get an eye exam?', a: 'Adults should have a comprehensive eye exam every 1-2 years. Those with diabetes, high blood pressure, or family history of eye disease may need annual exams.' },
        { q: 'Can screen time permanently damage my eyes?', a: 'Extended screen time causes digital eye strain but no permanent damage. Follow the 20-20-20 rule: every 20 minutes, look 20 feet away for 20 seconds.' },
        { q: 'Are carrots really good for eyesight?', a: 'Carrots are rich in vitamin A, which is essential for vision. However, they won\'t improve eyesight beyond normal — they help maintain healthy vision.' },
        { q: 'Do I need sunglasses on cloudy days?', a: 'Yes. UV rays penetrate clouds. UV exposure contributes to cataracts and macular damage over time, so wear UV-protective sunglasses year-round.' },
      ],
      myths: [
        { myth: 'Reading in dim light damages your eyes.', fact: 'Dim light causes eye strain but no permanent damage. Good lighting simply makes reading more comfortable.' },
        { myth: 'Wearing glasses makes your eyes weaker over time.', fact: 'Glasses correct vision; they don\'t change the eye\'s physical structure. Your eyes may change with age regardless.' },
        { myth: 'Only older adults get cataracts.', fact: 'While age-related cataracts are most common, they can also result from injury, medication, or congenital conditions at any age.' },
        { myth: 'Sitting too close to the TV damages eyes.', fact: 'Children often sit close because they can focus at near distance easily. It doesn\'t cause damage, though it may indicate nearsightedness.' },
      ],
      research: [
        { title: 'Blue Light and Digital Eye Strain', summary: 'Recent studies suggest blue light from screens causes less retinal damage than previously thought, but digital eye strain remains a significant concern.' },
        { title: 'Gene Therapy for Inherited Retinal Diseases', summary: 'FDA-approved gene therapy (Luxturna) offers hope for patients with specific inherited retinal dystrophies, marking a breakthrough in ophthalmology.' },
        { title: 'AI in Diabetic Retinopathy Screening', summary: 'Autonomous AI diagnostic systems now detect diabetic retinopathy with accuracy comparable to ophthalmologists, expanding access to screening.' },
      ],
      relatedConditions: ['Diabetic Retinopathy', 'Strabismus', 'Amblyopia (Lazy Eye)', 'Keratoconus', 'Uveitis'],
      emergencyCare: [
        'Chemical splash: flush eye with clean water for 15+ minutes, seek emergency care immediately',
        'Foreign object: do not rub — rinse with saline or water, seek medical help if it persists',
        'Sudden vision loss: go to emergency immediately — could indicate retinal detachment or stroke',
        'Eye injury/trauma: cover with a shield, do not apply pressure, seek immediate care',
        'Flash of light + new floaters: could indicate retinal tear — seek urgent evaluation',
      ],
      whenToVisit: [
        'Sudden changes in vision clarity',
        'Persistent eye pain or pressure',
        'Flashes of light or new floaters',
        'Eye injury or chemical exposure',
        'Persistent redness or discharge',
        'Halos around lights with headache',
      ],
      trustedResources: [
        { name: 'American Academy of Ophthalmology', url: 'https://www.aao.org' },
        { name: 'National Eye Institute', url: 'https://www.nei.nih.gov' },
        { name: 'WHO Vision and Blindness', url: 'https://www.who.int/health-topics/blindness-and-vision-loss' },
      ],
      videos: [
        { title: 'How the Human Eye Works', videoId: 'qAnpAYGw5kI' },
        { title: 'Common Eye Diseases Explained', videoId: 'i-unhWI_qLU' },
        { title: 'Eye Exercises for Better Vision', videoId: 'ETjm6jzlaO0' },
      ],
    },
  },
  {
    id: 'ear',
    name: 'Ear',
    tagline: 'Hear the rhythm of life',
    description:
      'The ear is the organ of hearing and balance. It detects sound vibrations and converts them into nerve impulses, while also maintaining equilibrium.',
    color: 'hsl(var(--sense-ear))',
    icon: 'Ear',
    sections: {
      overview:
        'The human ear is a complex organ responsible for both hearing and balance. It captures sound waves, amplifies them, and converts them into neural signals the brain interprets as sound. The ear also contains the vestibular system, which helps us maintain balance and spatial orientation.',
      anatomy: [
        'Outer ear (pinna/auricle) — collects and funnels sound waves',
        'Ear canal (external auditory meatus) — channels sound to the eardrum',
        'Tympanic membrane (eardrum) — vibrates in response to sound waves',
        'Ossicles (malleus, incus, stapes) — three tiny bones that amplify sound',
        'Cochlea — spiral-shaped organ converting vibrations to nerve impulses',
        'Semicircular canals — three fluid-filled tubes for balance detection',
        'Eustachian tube — equalizes pressure between middle ear and atmosphere',
        'Auditory nerve — transmits sound signals to the brain',
      ],
      functions: [
        'Sound detection across frequencies from 20 Hz to 20,000 Hz',
        'Sound localization — determining direction and distance of sounds',
        'Balance and spatial orientation via the vestibular system',
        'Sound amplification through the ossicular chain',
        'Pressure equalization through the Eustachian tube',
        'Voice modulation feedback during speech',
      ],
      diseases: [
        { name: 'Otitis Media', description: 'Middle ear infection, common in children, causing pain, fever, and temporary hearing loss.' },
        { name: 'Tinnitus', description: 'Ringing or buzzing in the ears without external sound, often from noise damage or age.' },
        { name: 'Presbycusis', description: 'Age-related hearing loss, typically affecting high frequencies first.' },
        { name: 'Meniere\'s Disease', description: 'Inner ear disorder causing vertigo, hearing loss, and tinnitus.' },
        { name: 'Otitis Externa (Swimmer\'s Ear)', description: 'Infection of the ear canal, often from water exposure.' },
        { name: 'Cerumen Impaction', description: 'Earwax buildup blocking the ear canal and reducing hearing.' },
        { name: 'Sensorineural Hearing Loss', description: 'Permanent hearing loss from damage to the inner ear or auditory nerve.' },
      ],
      symptoms: [
        'Hearing loss or muffled hearing',
        'Ear pain or pressure',
        'Ringing, buzzing, or hissing (tinnitus)',
        'Dizziness or vertigo',
        'Ear discharge or fluid drainage',
        'Difficulty understanding speech in noise',
        'Feeling of fullness in the ear',
      ],
      causes: [
        'Noise exposure (loud music, machinery, gunfire)',
        'Aging and natural degeneration',
        'Ear infections (bacterial or viral)',
        'Genetics and family history',
        'Head or ear trauma',
        'Certain medications (ototoxic drugs)',
        'Allergies and sinus infections',
      ],
      diagnosis: [
        'Otoscopic examination of the ear canal and eardrum',
        'Audiometry to measure hearing thresholds',
        'Tympanometry to assess eardrum movement',
        'Tuning fork tests (Rinne and Weber)',
        'Balance testing (electronystagmography)',
      ],
      tests: [
        'Pure Tone Audiometry — measures hearing at different frequencies',
        'Speech Audiometry — tests word recognition ability',
        'Tympanometry — evaluates middle ear function',
        'Otoacoustic Emissions (OAE) — screens inner ear hair cell function',
        'Auditory Brainstem Response (ABR) — tests auditory nerve pathways',
      ],
      treatment: [
        'Antibiotics for bacterial ear infections',
        'Hearing aids for sensorineural hearing loss',
        'Cochlear implants for severe hearing loss',
        'Earwax removal by a professional',
        'Surgery for structural issues (e.g., tympanoplasty)',
        'Tinnitus management with sound therapy',
        'Medications for Meniere\'s disease symptoms',
      ],
      prevention: [
        'Use ear protection in noisy environments (earplugs, earmuffs)',
        'Keep volume at 60% max on personal audio devices',
        'Dry ears after swimming to prevent infections',
        'Avoid inserting objects (cotton swabs) into the ear canal',
        'Treat allergies and sinus infections promptly',
        'Get regular hearing checks, especially after age 50',
      ],
      homeRemedies: [
        'Warm compress for ear pain relief',
        'Olive oil drops to soften earwax',
        'Steam inhalation for Eustachian tube congestion',
        'Garlic oil drops (natural antibacterial) for mild earaches',
        'Keep head elevated to reduce ear pressure',
      ],
      nutrition: [
        'Omega-3 fatty acids (fish, walnuts) — may slow age-related hearing loss',
        'Folate (spinach, lentils) — supports inner ear blood flow',
        'Magnesium (pumpkin seeds, almonds) — protects against noise damage',
        'Vitamin B12 (eggs, dairy) — deficiency linked to tinnitus',
        'Zinc (oysters, beef) — supports inner ear function',
        'Potassium (bananas, avocados) — regulates inner ear fluid',
      ],
      lifestyle: [
        'Limit exposure to loud noise and use protection',
        'Take listening breaks from headphones',
        'Manage stress, which can worsen tinnitus',
        'Exercise regularly to improve blood circulation to ears',
        'Quit smoking — it increases hearing loss risk',
        'Get adequate sleep for overall ear health',
      ],
      exercises: [
        'Eustachian tube equalization: yawn or swallow to pop ears',
        'Head turns: slowly turn head left and right 10 times',
        'Balance training: stand on one foot for 30 seconds each side',
        'Sound focus: close eyes and identify sounds from different directions',
        'Ear massage: gently massage around ears to improve circulation',
      ],
      faqs: [
        { q: 'Can loud music permanently damage hearing?', a: 'Yes. Prolonged exposure above 85 dB can cause permanent sensorineural hearing loss. Use the 60/60 rule: 60% volume for 60 minutes max.' },
        { q: 'Are cotton swabs safe for cleaning ears?', a: 'No. Earwax naturally migrates out. Cotton swabs push wax deeper and risk eardrum damage. Clean only the outer ear with a cloth.' },
        { q: 'Can tinnitus be cured?', a: 'There\'s no universal cure, but sound therapy, hearing aids, and stress management can significantly reduce its impact.' },
        { q: 'Do hearing aids restore normal hearing?', a: 'Hearing aids amplify sounds but don\'t restore natural hearing. They dramatically improve quality of life when properly fitted.' },
      ],
      myths: [
        { myth: 'Earwax is dirty and should be removed.', fact: 'Earwax is a natural protective substance that traps dust and bacteria. The ear self-cleans; only excess causing problems needs removal.' },
        { myth: 'Hearing loss only affects the elderly.', fact: 'Noise-induced hearing loss affects people of all ages. About 1 in 5 teens has some degree of hearing loss from personal audio devices.' },
        { myth: 'Only one type of hearing loss exists.', fact: 'There are three types: conductive (outer/middle ear), sensorineural (inner ear/nerve), and mixed. Treatment differs for each.' },
        { myth: 'Candling cleans the ear safely.', fact: 'Ear candling is ineffective and dangerous, risking burns and eardrum damage. Medical professionals advise against it.' },
      ],
      research: [
        { title: 'Hidden Hearing Loss', summary: 'Researchers have identified cochlear nerve damage without hair cell loss, explaining hearing difficulties even when standard tests are normal.' },
        { title: 'Gene Therapy for Hearing Loss', summary: 'Clinical trials using gene therapy to restore hearing in patients with specific genetic mutations show promising early results.' },
        { title: 'Tinnitus Brain Stimulation', summary: 'Non-invasive brain stimulation techniques are being studied as potential treatments for chronic tinnitus.' },
      ],
      relatedConditions: ['Vertigo', 'Labyrinthitis', 'Cholesteatoma', 'Mastoiditis', 'Acoustic Neuroma'],
      emergencyCare: [
        'Sudden hearing loss: seek medical care within 72 hours — early treatment improves recovery',
        'Severe ear injury: do not remove any object, seek immediate care',
        'Severe vertigo with vomiting: go to emergency — may indicate inner ear or neurological issue',
        'Ear with blood or clear fluid: could indicate skull fracture — seek emergency care',
        'Severe pain with swelling behind ear: could be mastoiditis — seek urgent care',
      ],
      whenToVisit: [
        'Sudden hearing loss in one or both ears',
        'Persistent ear pain or pressure',
        'Continuous tinnitus affecting sleep',
        'Recurrent ear infections',
        'Dizziness or balance problems',
        'Fluid or blood draining from the ear',
      ],
      trustedResources: [
        { name: 'American Academy of Otolaryngology', url: 'https://www.entnet.org' },
        { name: 'National Institute on Deafness', url: 'https://www.nidcd.nih.gov' },
        { name: 'WHO Deafness and Hearing Loss', url: 'https://www.who.int/health-topics/deafness-and-hearing-loss' },
      ],
      videos: [
        { title: 'How the Human Ear Works', videoId: 'TBZE7fTpMy8' },
        { title: 'Understanding Hearing Loss', videoId: '_kUy4p87_nk' },
        { title: 'Tinnitus Explained', videoId: 'NjvUXns5irg' },
      ],
    },
  },
  {
    id: 'nose',
    name: 'Nose',
    tagline: 'Breathe and savor life',
    description:
      'The nose is the organ of smell and a key part of the respiratory system. It filters, warms, and humidifies the air we breathe while detecting thousands of odors.',
    color: 'hsl(var(--sense-nose))',
    icon: 'Wind',
    sections: {
      overview:
        'The human nose serves dual functions: olfaction (smell) and respiration. It can distinguish over 1 trillion odors and plays a crucial role in taste perception. The nose also filters, warms, and humidifies inhaled air, protecting the lungs from harmful particles.',
      anatomy: [
        'External nose — visible structure of bone and cartilage',
        'Nasal cavity — large air-filled space above and behind the nose',
        'Nasal septum — divides the nasal cavity into two nostrils',
        'Turbinates (conchae) — bony structures that increase surface area',
        'Olfactory epithelium — tissue at the top of the nasal cavity with smell receptors',
        'Sinuses — air-filled spaces that lighten the skull and produce mucus',
        'Nasal mucosa — lining that warms and humidifies air',
        'Cilia — tiny hairs that move mucus and trapped particles',
      ],
      functions: [
        'Olfaction — detecting and distinguishing thousands of odors',
        'Air filtration — trapping dust, pollen, and microbes in mucus',
        'Air warming — bringing cold air to body temperature',
        'Air humidification — adding moisture to inhaled air',
        'Flavor enhancement — contributing to taste through retronasal olfaction',
        'Voice resonance — shaping the sound of speech',
      ],
      diseases: [
        { name: 'Allergic Rhinitis', description: 'Inflammation of the nasal mucosa from allergens like pollen, dust, or pet dander, causing sneezing and congestion.' },
        { name: 'Sinusitis', description: 'Inflammation or infection of the sinuses, causing facial pain, congestion, and nasal discharge.' },
        { name: 'Anosmia', description: 'Complete loss of the sense of smell, which can be temporary or permanent.' },
        { name: 'Nasal Polyps', description: 'Noncancerous growths in the nasal lining causing obstruction and reduced smell.' },
        { name: 'Deviated Septum', description: 'Displacement of the nasal septum causing breathing difficulty and congestion.' },
        { name: 'Non-allergic Rhinitis', description: 'Chronic sneezing and congestion without an allergic trigger.' },
      ],
      symptoms: [
        'Nasal congestion or blockage',
        'Runny nose or postnasal drip',
        'Loss or reduction of smell (anosmia)',
        'Facial pain or pressure',
        'Frequent sneezing',
        'Nosebleeds (epistaxis)',
        'Reduced ability to taste food',
      ],
      causes: [
        'Allergens (pollen, dust mites, pet dander, mold)',
        'Viral infections (common cold, flu)',
        'Bacterial sinus infections',
        'Environmental irritants (smoke, pollution, chemicals)',
        'Structural issues (deviated septum, polyps)',
        'Aging and natural olfactory decline',
        'Certain medications and nasal spray overuse',
      ],
      diagnosis: [
        'Physical examination of the nose and nasal cavity',
        'Nasal endoscopy for detailed interior view',
        'CT scan of sinuses to detect structural issues',
        'Allergy testing (skin prick or blood tests)',
        'Smell identification tests (UPSIT)',
      ],
      tests: [
        'Allergy Skin Prick Test — identifies specific allergens',
        'Nasal Endoscopy — visualizes nasal passages and sinuses',
        'CT Sinus Scan — reveals structural abnormalities',
        'Smell Identification Test (UPSIT) — assesses olfactory function',
        'Nasal Swab Culture — identifies bacterial or fungal infections',
      ],
      treatment: [
        'Antihistamines for allergic rhinitis',
        'Nasal corticosteroid sprays to reduce inflammation',
        'Saline nasal irrigation to flush irritants',
        'Antibiotics for bacterial sinusitis',
        'Surgery for polyps or deviated septum correction',
        'Smell training for olfactory recovery',
        'Allergen immunotherapy (allergy shots)',
      ],
      prevention: [
        'Identify and avoid known allergens',
        'Use a HEPA air purifier at home',
        'Wash hands regularly to prevent infections',
        'Avoid smoking and secondhand smoke',
        'Use a humidifier in dry conditions',
        'Stay hydrated to keep mucus thin',
        'Avoid overusing decongestant nasal sprays',
      ],
      homeRemedies: [
        'Saline nasal rinse (neti pot) to clear congestion',
        'Steam inhalation with eucalyptus oil',
        'Warm compress over sinuses for pain relief',
        'Ginger tea for anti-inflammatory benefits',
        'Elevate head while sleeping to reduce congestion',
        'Peppermint essential oil inhalation',
      ],
      nutrition: [
        'Vitamin C (citrus, bell peppers) — reduces histamine and inflammation',
        'Quercetin (onions, apples) — natural antihistamine',
        'Zinc (pumpkin seeds, lentils) — supports immune function',
        'Omega-3 fatty acids (fish, flaxseed) — reduces inflammation',
        'Vitamin A (carrots, sweet potatoes) — maintains mucosal health',
        'Spicy foods (horseradish, chili) — can temporarily clear congestion',
      ],
      lifestyle: [
        'Track and avoid personal allergy triggers',
        'Keep indoor air clean with HEPA filtration',
        'Shower after outdoor activities during pollen season',
        'Use dust-mite-proof bedding covers',
        'Manage stress, which can worsen allergic responses',
        'Exercise regularly to boost immune function',
      ],
      exercises: [
        'Alternate nostril breathing (Nadi Shodhana) for nasal clearing',
        'Deep breathing exercises to improve airflow',
        'Facial massage around sinuses to promote drainage',
        'Humming — creates vibrations that may help sinus ventilation',
        'Bhramari pranayama — bee breath for nasal health',
      ],
      faqs: [
        { q: 'Can loss of smell be permanent?', a: 'It depends on the cause. Viral infections, aging, and certain conditions can cause permanent loss. Smell training may help recovery in some cases.' },
        { q: 'Is a neti pot safe to use?', a: 'Yes, when used with distilled, sterile, or boiled water. Never use tap water, which can introduce dangerous organisms.' },
        { q: 'Why does food taste different when my nose is blocked?', a: 'Smell contributes up to 80% of flavor perception. When nasal passages are blocked, olfactory input decreases, reducing flavor.' },
        { q: 'Can nasal sprays be addictive?', a: 'Decongestant sprays can cause rebound congestion with overuse (beyond 3-5 days). Saline sprays are safe for long-term use.' },
      ],
      myths: [
        { myth: 'Green mucus means a bacterial infection.', fact: 'Green or yellow mucus can occur with viral infections too. Color alone doesn\'t distinguish viral from bacterial infections.' },
        { myth: 'You can\'t smell if you have a cold.', fact: 'Smell is reduced but rarely completely lost. Congestion blocks airflow to olfactory receptors; it returns as congestion clears.' },
        { myth: 'Nosebleeds are always serious.', fact: 'Most nosebleeds are minor and caused by dry air or nose-picking. Persistent or severe bleeding warrants medical evaluation.' },
        { myth: 'Smell loss from COVID is permanent.', fact: 'Most people recover their sense of smell within weeks to months. A small percentage experience long-term changes.' },
      ],
      research: [
        { title: 'COVID-19 and Olfactory Dysfunction', summary: 'Studies show COVID-19 can cause persistent smell loss through supporting cell damage, with smell training showing promise for recovery.' },
        { title: 'Smell Training for Anosmia', summary: 'Research confirms that repeated exposure to specific odors (rose, lemon, clove, eucalyptus) can improve olfactory recovery.' },
        { title: 'Microbiome of the Nasal Cavity', summary: 'The nasal microbiome plays a role in sinus health, and imbalances may contribute to chronic sinusitis.' },
      ],
      relatedConditions: ['Sleep Apnea', 'Asthma', 'Nasal Valve Collapse', 'Empty Nose Syndrome', 'Cerebrospinal Fluid Leak'],
      emergencyCare: [
        'Severe nosebleed: pinch nostrils, lean forward, apply ice — seek care if bleeding > 20 minutes',
        'Nose fracture: apply ice, keep head elevated — seek medical evaluation',
        'Clear fluid from nose after head injury: could be CSF leak — seek emergency care',
        'Foreign object in nose: do not try to remove deeply — seek medical help',
        'Sudden complete smell loss: consult a doctor to rule out serious causes',
      ],
      whenToVisit: [
        'Persistent nasal congestion beyond 10 days',
        'Chronic or recurring sinus pain',
        'Loss of smell lasting beyond an illness',
        'Frequent or severe nosebleeds',
        'Persistent postnasal drip',
        'Facial pain or pressure that worsens',
      ],
      trustedResources: [
        { name: 'American Rhinologic Society', url: 'https://www.american-rhinologic.org' },
        { name: 'American Academy of Otolaryngology', url: 'https://www.entnet.org' },
        { name: 'WHO Air Quality and Health', url: 'https://www.who.int/health-topics/air-pollution' },
      ],
      videos: [
        { title: 'How the Nose Works', videoId: 'zajxTUsbiQ8' },
        { title: 'Understanding Sinusitis', videoId: 'zaUeoNhE2Xo' },
        { title: 'Smell and Taste Connection', videoId: '0xcLbPkzN9w' },
      ],
    },
  },
  {
    id: 'tongue',
    name: 'Tongue',
    tagline: 'Taste the richness of life',
    description:
      'The tongue is a muscular organ essential for taste, speech, and digestion. It houses taste buds that detect sweet, sour, salty, bitter, and umami flavors.',
    color: 'hsl(var(--sense-tongue))',
    icon: 'Utensils',
    sections: {
      overview:
        'The tongue is a versatile muscular organ that plays a critical role in taste, speech, and the initial phase of digestion. It houses thousands of taste buds that can distinguish five basic tastes: sweet, sour, salty, bitter, and umami. The tongue also helps manipulate food for chewing and swallowing.',
      anatomy: [
        'Tip (apex) — front of the tongue, sensitive to touch and temperature',
        'Body — main muscular portion',
        'Root — back portion connected to the throat',
        'Papillae — small bumps containing taste buds',
        'Taste buds — sensory organs detecting five basic tastes',
        'Lingual tonsils — lymphoid tissue at the back',
        'Intrinsic muscles — change tongue shape',
        'Extrinsic muscles — move the tongue in different directions',
      ],
      functions: [
        'Taste perception via taste buds on papillae',
        'Speech articulation and pronunciation',
        'Food manipulation for chewing and swallowing',
        'Saliva distribution to begin digestion',
        'Temperature and texture sensing',
        'Oral hygiene through natural cleaning',
      ],
      diseases: [
        { name: 'Oral Thrush', description: 'Fungal infection (Candida) causing white patches on the tongue and mouth.' },
        { name: 'Glossitis', description: 'Inflammation of the tongue causing swelling, color changes, and pain.' },
        { name: 'Geographic Tongue', description: 'Benign condition with map-like patches on the tongue surface.' },
        { name: 'Oral Lichen Planus', description: 'Chronic inflammatory condition causing lacy white patches or sores.' },
        { name: 'Burning Mouth Syndrome', description: 'Persistent burning sensation without visible cause.' },
        { name: 'Oral Cancer', description: 'Cancer of the tongue or mouth, often linked to tobacco and alcohol.' },
        { name: 'Leukoplakia', description: 'Thickened, white patches on the tongue that may be precancerous.' },
      ],
      symptoms: [
        'Persistent bad breath (halitosis)',
        'White or colored patches on the tongue',
        'Burning or painful sensation',
        'Loss or change of taste (dysgeusia)',
        'Swelling or enlarged tongue',
        'Difficulty moving the tongue',
        'Sores or ulcers that don\'t heal',
      ],
      causes: [
        'Poor oral hygiene',
        'Fungal, bacterial, or viral infections',
        'Nutritional deficiencies (B12, iron, folate)',
        'Tobacco and alcohol use',
        'Allergic reactions to foods or dental products',
        'Acid reflux (GERD)',
        'Certain medications',
      ],
      diagnosis: [
        'Visual examination of the tongue and oral cavity',
        'Biopsy of suspicious lesions',
        'Cultures for fungal or bacterial infections',
        'Blood tests for nutritional deficiencies',
        'Allergy testing for suspected triggers',
      ],
      tests: [
        'Oral Examination — visual inspection of tongue and mouth',
        'Tongue Biopsy — tissue sample for suspicious lesions',
        'Taste Test — evaluates taste bud function',
        'Oral Swab Culture — identifies infections',
        'Blood Tests — checks for B12, iron, and folate deficiencies',
      ],
      treatment: [
        'Antifungal medications for oral thrush',
        'Anti-inflammatory medications for glossitis',
        'Nutritional supplements for deficiencies',
        'Topical treatments for burning mouth syndrome',
        'Surgery, radiation, or chemotherapy for oral cancer',
        'Improved oral hygiene practices',
        'Avoidance of irritants (tobacco, alcohol, spicy foods)',
      ],
      prevention: [
        'Brush teeth twice daily and clean the tongue',
        'Floss daily and use mouthwash',
        'Stay hydrated to maintain saliva production',
        'Avoid tobacco and excessive alcohol',
        'Eat a balanced diet rich in vitamins',
        'Visit the dentist every 6 months',
        'Replace toothbrush every 3 months',
      ],
      homeRemedies: [
        'Saltwater gargle for oral hygiene and soothing',
        'Baking soda rinse to balance oral pH',
        'Yogurt with probiotics for fungal infections',
        'Aloe vera juice for burning sensation',
        'Turmeric paste for anti-inflammatory benefits',
        'Oil pulling with coconut oil for oral health',
      ],
      nutrition: [
        'Vitamin B12 (meat, fish, dairy) — prevents glossitis and taste loss',
        'Iron (spinach, lentils, red meat) — prevents tongue inflammation',
        'Folate (leafy greens, beans) — supports tissue health',
        'Zinc (pumpkin seeds, chickpeas) — essential for taste function',
        'Vitamin C (citrus, berries) — maintains gum and tongue health',
        'Probiotics (yogurt, kefir) — balance oral microbiome',
      ],
      lifestyle: [
        'Maintain excellent oral hygiene',
        'Stay well-hydrated throughout the day',
        'Limit sugary and acidic foods',
        'Avoid very hot or spicy foods if sensitive',
        'Manage stress, which can trigger oral conditions',
        'Quit smoking and limit alcohol',
      ],
      exercises: [
        'Tongue stretching: stick tongue out and hold for 5 seconds',
        'Tongue sweep: move tongue in a full circle around the mouth',
        'Tongue press: press tongue against the roof of the mouth',
        'Side-to-side: move tongue from one corner to the other',
        'Taste training: sample different flavors mindfully',
      ],
      faqs: [
        { q: 'Can taste buds regenerate?', a: 'Yes. Taste buds have a 10-14 day lifecycle and regenerate. However, aging and certain conditions can reduce their number over time.' },
        { q: 'Is geographic tongue dangerous?', a: 'No. Geographic tongue is a benign condition that causes no harm. It may cause mild discomfort with certain foods but requires no treatment.' },
        { q: 'Why do I have a white coating on my tongue?', a: 'A white coating often results from poor hygiene, dry mouth, or oral thrush. Regular tongue cleaning usually resolves it. Persistent patches need evaluation.' },
        { q: 'Can loss of taste indicate a serious condition?', a: 'It can. Taste loss may result from infections, deficiencies, medications, or neurological issues. Persistent changes should be evaluated by a doctor.' },
      ],
      myths: [
        { myth: 'Different parts of the tongue taste different flavors.', fact: 'The "tongue map" is a myth. All taste qualities can be detected across all taste bud regions, though sensitivity varies slightly.' },
        { myth: 'A white tongue always means thrush.', fact: 'A white coating can result from many causes including dehydration, poor hygiene, or diet. Thrush requires specific fungal identification.' },
        { myth: 'Metal taste in mouth is always from dental work.', fact: 'Metallic taste can result from medications, supplements, GERD, infections, or neurological conditions. Persistent symptoms need evaluation.' },
        { myth: 'Tongue cleaning is unnecessary.', fact: 'Cleaning the tongue removes bacteria and food particles, reducing bad breath and improving oral health significantly.' },
      ],
      research: [
        { title: 'Gut-Oral Axis and Taste', summary: 'Research reveals connections between oral microbiome, taste perception, and systemic health, including metabolic conditions.' },
        { title: 'Taste Disorders and COVID-19', summary: 'Studies show taste dysfunction is a prominent COVID-19 symptom, with recovery patterns varying significantly among patients.' },
        { title: 'Taste Bud Regeneration Research', summary: 'Scientists are exploring stem cell therapies to regenerate taste buds, offering hope for patients with permanent taste loss.' },
      ],
      relatedConditions: ['Oral Candidiasis', 'Sjogren\'s Syndrome', 'Vitamin B12 Deficiency', 'GERD', 'Oral Submucous Fibrosis'],
      emergencyCare: [
        'Severe tongue swelling (angioedema): seek emergency care — can block airway',
        'Deep tongue laceration: apply pressure, seek medical care for stitches',
        'Tongue burn from hot food: rinse with cool water, apply ice — seek care if severe',
        'Sudden inability to move tongue: could indicate stroke — call emergency immediately',
        'Persistent ulcer beyond 2 weeks: needs evaluation to rule out oral cancer',
      ],
      whenToVisit: [
        'Persistent white or red patches',
        'Sores or ulcers lasting more than 2 weeks',
        'Persistent taste changes or loss',
        'Burning sensation without obvious cause',
        'Difficulty swallowing or moving the tongue',
        'Unexplained tongue swelling',
      ],
      trustedResources: [
        { name: 'American Dental Association', url: 'https://www.ada.org' },
        { name: 'Oral Cancer Foundation', url: 'https://oralcancerfoundation.org' },
        { name: 'WHO Oral Health', url: 'https://www.who.int/health-topics/oral-health' },
      ],
      videos: [
        { title: 'How the Tongue Works', videoId: 'SneTFJc7u7Y' },
        { title: 'Understanding Taste Buds', videoId: 'JJyQz0152t8' },
        { title: 'Oral Health and Hygiene', videoId: 'zVCaYyUWWSw' },
      ],
    },
  },
  {
    id: 'skin',
    name: 'Skin',
    tagline: 'Your body\'s living armor',
    description:
      'The skin is the body\'s largest organ, serving as a protective barrier and sensory interface. It detects touch, temperature, pain, and pressure while regulating body temperature.',
    color: 'hsl(var(--sense-skin))',
    icon: 'Hand',
    sections: {
      overview:
        'The skin is the largest organ of the human body, covering about 2 square meters and weighing roughly 4 kg. It serves as a protective barrier against pathogens, regulates body temperature, and houses sensory receptors for touch, pressure, pain, and temperature. The skin also produces vitamin D when exposed to sunlight.',
      anatomy: [
        'Epidermis — outermost layer, provides waterproof barrier and skin tone',
        'Dermis — beneath epidermis, contains hair follicles, sweat glands, and blood vessels',
        'Hypodermis (subcutaneous) — deepest layer of fat and connective tissue',
        'Melanocytes — cells producing melanin for skin pigmentation',
        'Sebaceous glands — produce sebum to moisturize skin and hair',
        'Sweat glands — regulate body temperature through perspiration',
        'Hair follicles — produce hair and associated with sebaceous glands',
        'Sensory receptors — detect touch, pressure, temperature, and pain',
      ],
      functions: [
        'Protection — barrier against pathogens, UV radiation, and chemicals',
        'Temperature regulation — through sweating and blood vessel dilation',
        'Sensation — detecting touch, pressure, pain, and temperature',
        'Vitamin D synthesis — triggered by UV exposure',
        'Excretion — removing small amounts of waste through sweat',
        'Immunity — housing immune cells that detect and fight pathogens',
      ],
      diseases: [
        { name: 'Acne', description: 'Common skin condition from clogged hair follicles and sebaceous glands, causing pimples and inflammation.' },
        { name: 'Eczema (Atopic Dermatitis)', description: 'Chronic inflammatory condition causing dry, itchy, red skin.' },
        { name: 'Psoriasis', description: 'Autoimmune condition causing rapid skin cell turnover and scaly plaques.' },
        { name: 'Melanoma', description: 'Most serious type of skin cancer, developing in melanocytes.' },
        { name: 'Contact Dermatitis', description: 'Skin reaction from contact with irritants or allergens.' },
        { name: 'Rosacea', description: 'Chronic condition causing facial redness and visible blood vessels.' },
        { name: 'Fungal Infections', description: 'Infections like ringworm, athlete\'s foot, and yeast infections.' },
      ],
      symptoms: [
        'Persistent itching or irritation',
        'Redness, rashes, or inflammation',
        'Dry, flaky, or scaly skin',
        'New or changing moles',
        'Bumps, blisters, or sores',
        'Skin discoloration or pigmentation changes',
        'Excessive oiliness or dryness',
      ],
      causes: [
        'Genetics and family history',
        'Hormonal changes (puberty, pregnancy, menopause)',
        'Allergens and irritants',
        'UV sun exposure',
        'Infections (bacterial, viral, fungal)',
        'Stress and immune system dysfunction',
        'Poor diet and dehydration',
      ],
      diagnosis: [
        'Visual examination of skin lesions',
        'Dermoscopy for detailed mole examination',
        'Skin biopsy for suspicious lesions',
        'Allergy patch testing',
        'Wood\'s lamp examination for fungal infections',
      ],
      tests: [
        'Skin Biopsy — tissue sample for microscopic examination',
        'Patch Test — identifies contact allergens',
        'Wood\'s Lamp Exam — detects fungal infections',
        'Dermoscopy — magnified view of skin lesions',
        'Skin Culture — identifies bacterial or fungal organisms',
      ],
      treatment: [
        'Topical corticosteroids for inflammation',
        'Retinoids for acne and anti-aging',
        'Antibiotics for bacterial infections',
        'Antifungal medications for fungal infections',
        'Phototherapy for psoriasis and eczema',
        'Surgical excision for skin cancers',
        'Moisturizers and barrier creams for dry skin',
      ],
      prevention: [
        'Apply broad-spectrum SPF 30+ sunscreen daily',
        'Avoid tanning beds and excessive sun exposure',
        'Keep skin clean and moisturized',
        'Stay hydrated by drinking enough water',
        'Eat a balanced diet rich in antioxidants',
        'Avoid sharing personal items to prevent infections',
        'Perform regular skin self-examinations',
      ],
      homeRemedies: [
        'Aloe vera gel for sunburn and irritation',
        'Oatmeal baths for eczema and itching',
        'Coconut oil for dry skin and mild fungal issues',
        'Honey mask for antibacterial benefits',
        'Tea tree oil for acne (diluted)',
        'Cold compress for inflammation and itching',
      ],
      nutrition: [
        'Vitamin C (citrus, berries) — collagen production and antioxidant',
        'Vitamin E (almonds, avocados) — protects skin from oxidative damage',
        'Omega-3 fatty acids (fish, walnuts) — reduces inflammation',
        'Vitamin A (carrots, sweet potatoes) — supports skin cell production',
        'Zinc (pumpkin seeds, lentils) — aids wound healing',
        'Selenium (Brazil nuts, fish) — protects against UV damage',
      ],
      lifestyle: [
        'Use sunscreen every day, even on cloudy days',
        'Moisturize immediately after bathing',
        'Avoid hot showers that strip skin oils',
        'Manage stress, which can trigger flare-ups',
        'Get 7-8 hours of sleep for skin repair',
        'Avoid smoking, which accelerates skin aging',
      ],
      exercises: [
        'Facial massage to improve circulation',
        'Yoga for stress reduction and skin glow',
        'Cardio exercise to boost blood flow to skin',
        'Facial yoga for muscle tone',
        'Dry brushing before shower for exfoliation',
      ],
      faqs: [
        { q: 'How often should I apply sunscreen?', a: 'Apply sunscreen every morning and reapply every 2 hours outdoors, or after swimming/sweating. Use SPF 30+ broad-spectrum.' },
        { q: 'Can diet affect my skin?', a: 'Yes. High-glycemic foods and dairy may worsen acne. Antioxidant-rich foods, omega-3s, and adequate water support healthy skin.' },
        { q: 'Are moles always a sign of cancer?', a: 'No. Most moles are benign. Use the ABCDE rule: Asymmetry, Border, Color, Diameter, Evolving. Changes warrant evaluation.' },
        { q: 'Does drinking water improve skin?', a: 'Adequate hydration supports skin function, but over-drinking won\'t dramatically change skin. Combine with good skincare for best results.' },
      ],
      myths: [
        { myth: 'You don\'t need sunscreen on cloudy days.', fact: 'Up to 80% of UV rays penetrate clouds. Daily sunscreen is essential regardless of weather.' },
        { myth: 'Chocolate causes acne.', fact: 'Pure chocolate hasn\'t been conclusively linked to acne. High-sugar and high-dairy foods are more likely triggers.' },
        { myth: 'Natural oils can replace sunscreen.', fact: 'No natural oil provides adequate UV protection. Always use tested sunscreen with SPF 30 or higher.' },
        { myth: 'Skin type never changes.', fact: 'Skin type can change with age, hormones, climate, and products. Adjust your routine as your skin changes.' },
      ],
      research: [
        { title: 'Skin Microbiome and Health', summary: 'Research reveals the skin microbiome\'s role in immune regulation, with implications for treating eczema, acne, and psoriasis.' },
        { title: 'Nanotechnology in Sunscreens', summary: 'Advances in nanoparticle UV filters offer better protection with less white residue, improving sunscreen compliance.' },
        { title: 'Immunotherapy for Melanoma', summary: 'Checkpoint inhibitors have revolutionized melanoma treatment, dramatically improving survival rates for advanced disease.' },
      ],
      relatedConditions: ['Scleroderma', 'Vitiligo', 'Hidradenitis Suppurativa', 'Cellulitis', 'Seborrheic Dermatitis'],
      emergencyCare: [
        'Severe burn: cool with running water for 20 minutes, do not apply ice or butter — seek care for large or deep burns',
        'Severe allergic skin reaction: seek emergency care if spreading rapidly or affecting breathing',
        'Sudden spreading rash with fever: could indicate serious infection — seek urgent care',
        'Large area of skin peeling: could indicate Stevens-Johnson syndrome — emergency',
        'Suspected melanoma with rapid changes: seek prompt dermatological evaluation',
      ],
      whenToVisit: [
        'New or changing moles (ABCDE signs)',
        'Persistent rashes or skin irritation',
        'Severe or cystic acne',
        'Spreading skin infections',
        'Skin changes affecting quality of life',
        'Chronic dry, itchy, or painful skin',
      ],
      trustedResources: [
        { name: 'American Academy of Dermatology', url: 'https://www.aad.org' },
        { name: 'Skin Cancer Foundation', url: 'https://www.skincancer.org' },
        { name: 'WHO UV Radiation and Health', url: 'https://www.who.int/health-topics/ultraviolet-radiation' },
      ],
      videos: [
        { title: 'How the Skin Works', videoId: 'u4GQAScgVC4' },
        { title: 'Understanding Skin Cancer', videoId: 'x8YDsZtrzJQ' },
        { title: 'Skincare Science Explained', videoId: 'KAyTvaTaS7o' },
      ],
    },
  },
];

export function getOrgan(id: string): SenseOrgan | undefined {
  return senseOrgans.find((o) => o.id === id);
}
